# terraform/azure/providers.tf
# This file is automatically generated and should not be manually edited.
# You can override the provider configuration by creating a new file
# named `azurerm-provider-override.tf` in the same directory.

terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "3.80.0"
    }
  }
}

provider "azurerm" {
  features {}
  # Add your subscription ID here to resolve the authentication error.
  subscription_id = "736b4173-e1ed-46ae-be69-2241d0f855e8"
  # This flag prevents Terraform from attempting to register Resource Providers
  # for which you may not have permissions.
  skip_provider_registration = true
}
