name: CI Pipeline
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
<<<<<<< HEAD
=======
    defaults:
      run:
        working-directory: todo
>>>>>>> c635cc783b101bd7840b2c6bae147caed31f65d4
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
<<<<<<< HEAD
          node-version: "18"
          cache: "npm"
=======
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: todo/package-lock.json
      - name: Debug: List files in todo directory
        run: ls -la
      - name: Debug: Check Node and npm versions
        run: |
          node -v
          npm -v
>>>>>>> c635cc783b101bd7840b2c6bae147caed31f65d4
      - name: Install dependencies
        run: npm ci
      - name: Run linting
        run: npm run lint
      - name: Run tests
<<<<<<< HEAD
        run: npm test
=======
        run: npm test
>>>>>>> c635cc783b101bd7840b2c6bae147caed31f65d4
