name: CI Pipeline

on:
  pull_request:
    branches: [main, develop]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Debug repository structure
        run: ls -la
      - name: Check frontend directory
        run: ls -la ./frontend || echo "Frontend directory not found"
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend
      - name: Run frontend linting
        run: npm run lint
        working-directory: ./frontend
      - name: Run frontend tests
        run: npm test
        working-directory: ./frontend
