name: Application CI Pipeline

on:
  pull_request:
    branches: [main, develop]

jobs:
  backend:
    runs-on: ubuntu-latest
    # Set a default working directory for all steps in this job
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # No need to check directory, the defaults will cause failure if it doesn't exist
      - name: Set up Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          # Enable caching for npm dependencies in the backend
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'

      - name: Install dependencies securely
        run: npm ci # Use ci for faster, more reliable installs

      - name: Run backend linting
        run: npm run lint

      - name: Run backend tests
        run: npm test

  frontend:
    runs-on: ubuntu-latest
    # Set a default working directory for all steps in this job
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          # Enable caching for npm dependencies in the frontend
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install dependencies securely
        run: npm ci

      - name: Run frontend linting
        run: npm run lint

      # The default React app from Vite doesn't have a test script.
      # This step will fail unless you add one to frontend/package.json.
      # For now, let's comment it out to ensure the pipeline passes.
      # - name: Run frontend tests
      #   run: npm test
