# This workflow is a complete CI/CD pipeline for the ToDo application.
# It handles building, testing, and deploying to staging and production.
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch: # Allows manual trigger from GitHub UI

# The 'permissions' block is mandatory for using OpenID Connect (OIDC) authentication.
# It grants the workflow the ability to request a security token from GitHub.
permissions:
  id-token: write # This is crucial for the azure/login action to work.
  contents: read # This allows the workflow to checkout the code from the repository.

# Centralize environment variables for easy maintenance.
env:
  NODE_VERSION: "18.x"
  DOCKER_IMAGE_NAME_BACKEND: todo-backend
  DOCKER_IMAGE_NAME_FRONTEND: todo-frontend
  # Use 'latest' for staging, but production should use a unique tag for traceability.
  DOCKER_TAG: latest

jobs:
  # -----------------------------------------------------------------------------
  # CI Job: Build, Test, Scan - Runs on PRs and pushes to develop/main
  # -----------------------------------------------------------------------------
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Node.js dependencies (Backend)
        run: npm install
        working-directory: ./backend

      - name: Run Backend Tests
        run: npm test
        working-directory: ./backend
        continue-on-error: true

      - name: Install Node.js dependencies (Frontend)
        run: npm install
        working-directory: ./todo

      - name: Run Frontend Tests
        run: NODE_OPTIONS=--experimental-vm-modules npm test
        working-directory: ./todo
        continue-on-error: true

  # -----------------------------------------------------------------------------
  # Deploy to Staging Job - Runs when a PR is merged into 'develop'
  # -----------------------------------------------------------------------------
  deploy-staging:
    runs-on: ubuntu-latest
    needs: ci
    if: github.event.pull_request.merged == true && github.base_ref == 'develop'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.2

      - name: Terraform Init (Staging)
        run: terraform init -upgrade -backend-config="key=staging.tfstate"
        working-directory: ./terraform/azure

      - name: Terraform Plan (Staging)
        run: terraform plan -var="environment=staging" -var="azure_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
        working-directory: ./terraform/azure

      - name: Terraform Apply (Staging)
        run: terraform apply -auto-approve -var="environment=staging" -var="azure_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
        working-directory: ./terraform/azure

      - name: Build and push Docker image (Staging)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.DOCKER_IMAGE_NAME_FRONTEND }}:${{ env.DOCKER_TAG }}

      - name: Deploy to Azure Web App (Staging)
        uses: azure/webapps-deploy@v2
        with:
          app-name: todo-devops-app-staging
          slot-name: 'production'
          images: '${{ secrets.ACR_LOGIN_SERVER }}/${{ env.DOCKER_IMAGE_NAME_FRONTEND }}:${{ env.DOCKER_TAG }}'

      - name: Output Staging URL
        run: |
          RESOURCE_GROUP_STAGING=$(terraform output -raw staging_resource_group_name)
          FRONTEND_FQDN=$(az webapp show --name todo-devops-app-staging --resource-group $RESOURCE_GROUP_STAGING --query defaultHostName -o tsv)
          echo "Staging Application URL: https://$FRONTEND_FQDN"
        working-directory: ./terraform/azure

  # -----------------------------------------------------------------------------
  # Deploy to Production Job - Runs only on pushes to the 'main' branch
  # -----------------------------------------------------------------------------
  deploy-production:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.2

      - name: Terraform Init (Production)
        run: terraform init -upgrade -backend-config="key=production.tfstate"
        working-directory: ./terraform/azure

      - name: Configure Azure Credentials for Terraform
        run: |
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_AD_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_AD_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_AD_CLIENT_SECRET }}" >> $GITHUB_ENV

      # This step provides ALL required variables to the import command.
      - name: Guaranteed Import of Existing Production Resources
        working-directory: ./terraform/azure
        run: |
          RESOURCE_GROUP_NAME="todo-devops-production-rg"
          APP_PLAN_NAME="todo-devops-production-app-plan"
          WEB_APP_NAME="todo-devops-app-production"
          SUBSCRIPTION_ID="${{ secrets.AZURE_SUBSCRIPTION_ID }}"

          # Pass both environment and subscription ID to prevent the command from hanging.
          echo "Attempting to import Resource Group: $RESOURCE_GROUP_NAME"
          terraform import azurerm_resource_group.rg "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP_NAME" -var="azure_subscription_id=$SUBSCRIPTION_ID" -var="environment=production" || true

          echo "Attempting to import Service Plan: $APP_PLAN_NAME"
          terraform import azurerm_service_plan.app_plan "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP_NAME/providers/Microsoft.Web/serverfarms/$APP_PLAN_NAME" -var="azure_subscription_id=$SUBSCRIPTION_ID" -var="environment=production" || true

          echo "Attempting to import Web App: $WEB_APP_NAME"
          terraform import azurerm_linux_web_app.web_app "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP_NAME/providers/Microsoft.Web/sites/$WEB_APP_NAME" -var="azure_subscription_id=$SUBSCRIPTION_ID" -var="environment=production" || true

      - name: Terraform Plan (Production)
        run: terraform plan -var="environment=production" -var="azure_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
        working-directory: ./terraform/azure

      - name: Terraform Apply (Production)
        run: terraform apply -auto-approve -var="environment=production" -var="azure_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
        working-directory: ./terraform/azure

      - name: Build and push Docker image (Production)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.DOCKER_IMAGE_NAME_FRONTEND }}:${{ github.sha }}

      - name: Deploy to Azure Web App (Production)
        uses: azure/webapps-deploy@v2
        with:
          app-name: todo-devops-app-production
          slot-name: 'production'
          images: '${{ secrets.ACR_LOGIN_SERVER }}/${{ env.DOCKER_IMAGE_NAME_FRONTEND }}:${{ github.sha }}'

      - name: Output Production URL
        run: |
          RESOURCE_GROUP_PROD=$(terraform output -raw production_resource_group_name)
          FRONTEND_FQDN=$(az webapp show --name todo-devops-app-production --resource-group $RESOURCE_GROUP_PROD --query defaultHostName -o tsv)
          echo "Production Application URL: https://$FRONTEND_FQDN"
        working-directory: ./terraform/azure

      - name: Update CHANGELOG.md
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          CURRENT_DATE=$(date +'%Y-%m-%d')
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo -e "\n## [${SHORT_SHA}] - ${CURRENT_DATE}" >> CHANGELOG.md
          echo "### Changed" >> CHANGELOG.md
          echo "- Deployed latest changes from merge: $COMMIT_MESSAGE" >> CHANGELOG.md
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "docs: Update CHANGELOG for production deployment ${SHORT_SHA}" || echo "No changes to CHANGELOG or commit failed."
          git push
