# The azurerm provider block
provider "azurerm" {
  features {}
}

# This resource generates a unique random string to append to resource names.
# This helps prevent naming conflicts in Azure.
resource "random_string" "app_suffix" {
  length  = 6
  special = false
  upper   = false
  number  = true
}

# The main resource group for the project.
resource "azurerm_resource_group" "rg" {
  name     = "todo-devops-rg-${random_string.app_suffix.result}"
  location = "East US"
}

# An App Service Plan defines the underlying virtual machines for your App Services.
# The "B1" sku is a basic, cost-effective option for development.
resource "azurerm_service_plan" "app_plan" {
  name                = "todo-devops-app-plan-${random_string.app_suffix.result}"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  sku_name            = "B1"
  os_type             = "Linux"
}

# This is the web application itself, which will run inside the App Service Plan.
# It's configured to run a Node.js 18 LTS app.
resource "azurerm_linux_web_app" "app_service" {
  name                = "todo-devops-app-${random_string.app_suffix.result}"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  service_plan_id     = azurerm_service_plan.app_plan.id
  enabled             = true

  site_config {
    application_stack {
      node_version = "18-lts"
    }
  }
}

# This is the storage account used by Terraform for remote state management.
resource "azurerm_storage_account" "tfstate" {
  name                     = "tdopsbienaimeetfstate"
  resource_group_name      = azurerm_resource_group.rg.name
  location                 = azurerm_resource_group.rg.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

# This creates the blob container inside the storage account to hold the state file.
resource "azurerm_storage_container" "tfstate" {
  name                  = "tfstate"
  storage_account_name  = azurerm_storage_account.tfstate.name
  container_access_type = "private"
}
