name: "Terraform"

on:
  push:
    branches:
      - ft/pipelineb

env:
  TF_LOG: INFO
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  STORAGE_ACCOUNT_NAME: tdopsbienaimeetfstate

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: "Terraform Init"
        run: terraform init -backend-config="resource_group_name=todo-devops-rg" -backend-config="storage_account_name=${{ env.STORAGE_ACCOUNT_NAME }}" -backend-config="container_name=tfstate" -backend-config="key=staging.tfstate"
        working-directory: terraform/azure/

      - name: "Terraform Plan"
        run: terraform plan
        working-directory: terraform/azure/

      - name: "Terraform Apply"
        run: terraform apply -auto-approve
        working-directory: terraform/azure/
