# This workflow is a complete CI/CD pipeline for the ToDo application.
# It handles building, testing, and deploying to staging and production.
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop # Only run CI on PRs to the staging branch
  workflow_dispatch: # Allows manual trigger from GitHub UI

permissions:
  id-token: write
  contents: write

env:
  NODE_VERSION: "18.x"
  DOCKER_IMAGE_NAME: todo-app
  DOCKER_TAG_STAGING: latest
  DOCKER_TAG_PRODUCTION: ${{ github.sha }}

jobs:
  # -----------------------------------------------------------------------------
  # CI Job: Build, Test, Scan - Runs on PRs and pushes to develop/main
  # -----------------------------------------------------------------------------
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Node.js dependencies
        run: npm install
        working-directory: ./todo

      - name: Run Application Tests
        run: npm test
        working-directory: ./todo
        continue-on-error: true

      - name: Snyk Dependency Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=./todo/package-lock.json

  # -----------------------------------------------------------------------------
  # Docker Build & Push - Runs after CI and pushes image to Azure Container Registry
  # -----------------------------------------------------------------------------
  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ACR Login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.ref == 'refs/heads/main' && env.DOCKER_TAG_PRODUCTION || env.DOCKER_TAG_STAGING }}

      - name: Snyk Container Scan
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.ref == 'refs/heads/main' && env.DOCKER_TAG_PRODUCTION || env.DOCKER_TAG_STAGING }}

  # -----------------------------------------------------------------------------
  # Deploy to Staging Job - Runs on pushes to 'develop'
  # -----------------------------------------------------------------------------
  deploy-staging:
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    if: github.ref == 'refs/heads/develop'
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App (Staging)
        uses: azure/webapps-deploy@v2
        with:
          app-name: todo-devops-app-staging
          images: '${{ secrets.ACR_LOGIN_SERVER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG_STAGING }}'
          
      - name: Output Staging URL
        run: echo "Staging Application URL: https://todo-devops-app-staging.azurewebsites.net"

  # -----------------------------------------------------------------------------
  # Deploy to Production Job - Runs only on pushes to the 'main' branch
  # -----------------------------------------------------------------------------
  deploy-production:
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    if: github.ref == 'refs/heads/main'

    environment:
      name: production
      url: https://todo-devops-app-production.azurewebsites.net

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App (Production)
        uses: azure/webapps-deploy@v2
        with:
          app-name: todo-devops-app-production
          images: '${{ secrets.ACR_LOGIN_SERVER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG_PRODUCTION }}'

      - name: Output Production URL
        run: echo "Production Application URL: https://todo-devops-app-production.azurewebsites.net"

      - name: Update CHANGELOG.md
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          CURRENT_DATE=$(date +'%Y-%m-%d')
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo -e "\n## [${SHORT_SHA}] - ${CURRENT_DATE}" >> CHANGELOG.md
          echo "### Changed" >> CHANGELOG.md
          echo "- Deployed latest changes from merge: $COMMIT_MESSAGE" >> CHANGELOG.md
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "docs: Update CHANGELOG for production deployment ${SHORT_SHA} [skip ci]" || echo "No changes to CHANGELOG or commit failed."
          git push
